alter table events drop constraint if exists fk_event_category_id;
alter table events drop constraint if exists fk_event_initiator;
alter table events drop constraint if exists fk_event_location_id;

-- COMPILATIONS
drop table if exists compilations;

create table if not exists compilations
(
    id      bigint generated by default as identity not null,
    pinned  boolean,
    title   varchar(255) default null,
    constraint pk_compilation_id primary key (id),
    unique (title)
);

-- CATEGORIES
drop table if exists categories;

create table if not exists categories
(
    id      bigint generated by default as identity not null,
    name    varchar(255) default null,
    constraint pk_category_id primary key(id),
    unique (name)
);

-- LOCATIONS
drop table if exists locations;

create table if not exists locations
(
    id bigint generated by default as identity not null,
    lat real not null,
    lon real not null,
    constraint pk_location_id primary key (id)
);

-- USERS
drop table if exists users;

create table if not exists users
(
    id bigint generated by default as identity not null,
    name varchar(100) not null,
    email varchar(255) not null,
    constraint pk_usera_id primary key (id),
    unique (email)
);

-- EVENTS
drop table if exists events;

create table if not exists events
(
    id                  bigint generated by default as identity not null,
    title               varchar(255) not null,
    annotation          varchar(300) default null,
    description         text default null,
    category_id         bigint default null,
    confirmed_request   int default 0,
    event_date          timestamp without time zone not null,
    initiator bigint    default null,
    location_id bigint  default null,
    pid                 boolean,
    participant_limit   int default 0,
    published_on        timestamp without time zone default null,
    request_moderation  boolean default true,
    state               varchar(50) not null,
    views               int default 0,
    created_at          timestamp without time zone not null,
    constraint pk_event_id primary key (id),
    constraint fk_event_category_id foreign key (id) references categories (id) on delete set null,
    constraint fk_event_initiator foreign key (id) references users (id) on delete set null,
    constraint fk_event_location_id foreign key (id) references locations (id) on delete set null
);