version: '3.8'
services:
  statistics-server:
    build: statistics
    image: statistics
    container_name: explorewithme-stats
    depends_on:
      - statistics-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statistics-db:5432/stats
      - POSTGRES_DB=stats
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=stats
  statistics-db:
    image: postgres:14-alpine
    container_name: statistics-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=stats
    volumes:
      - /var/lib/postgresql/data/
  statistics-main:
    build: main-service
    image: main-service
    container_name: explorewithme-main
    depends_on:
      - main-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main
      - POSTGRES_DB=main
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=main
  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=main
    volumes:
      - /var/lib/postgresql/data/
  subscribtion:
    build: subscription
    image: subscription
    container_name: explorewithme-subscriber
    depends_on:
      - subscriber-db
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://subscriber-db:5432/subscriber
      - POSTGRES_DB=subscriber
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=subscriber
  subscriber-db:
    image: postgres:14-alpine
    container_name: subscriber-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=subscriber
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=subscriber
    volumes:
      - /var/lib/postgresql/data/
