version: '3.1'
services:
  statistics-server:
    ports:
      - "9090:9090"

  statistics-db:
    image: postgres:14-alpine
    container_name: statistics-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=stats
    volumes:
      - /var/lib/postgresql/data/
