drop table if exists hits;

create table hits
(
    id              bigint generated by default as identity not null,
    app             varchar(100) not null,
    uri             varchar(100) not null,
    ip              varchar(20) not null,
    timestamp     timestamp without time zone not null,
    constraint pk_id primary key (id)
);